"""simplify_event_model

Revision ID: 0a18de13569d
Revises: a084714c552c
Create Date: 2026-02-14 15:26:53.608176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a18de13569d'
down_revision: Union[str, None] = 'a084714c552c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('event_organizer_team_id_fkey'), 'event', type_='foreignkey')
    op.drop_column('event', 'enable_awards_nomination')
    op.drop_column('event', 'notes')
    op.drop_column('event', 'organizer_team_id')
    op.drop_column('event', 'expectations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('expectations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('organizer_team_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('enable_awards_nomination', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('event_organizer_team_id_fkey'), 'event', 'team', ['organizer_team_id'], ['id'])
    # ### end Alembic commands ###
