"""Add endorsement context and social

Revision ID: 1be0a32c5e8b
Revises: df7de49f6342
Create Date: 2026-02-14 18:07:41.468712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be0a32c5e8b'
down_revision: Union[str, None] = 'df7de49f6342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('endorsement_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_comment_endorsement_id'), 'comment', ['endorsement_id'], unique=False)
    op.create_foreign_key(None, 'comment', 'endorsements', ['endorsement_id'], ['id'], ondelete='CASCADE')
    op.add_column('endorsements', sa.Column('project_id', sa.String(), nullable=True))
    op.add_column('endorsements', sa.Column('event_id', sa.String(), nullable=True))
    op.add_column('endorsements', sa.Column('skills', sa.String(), nullable=True))
    op.drop_index(op.f('ix_endorsements_category'), table_name='endorsements')
    op.create_index(op.f('ix_endorsements_event_id'), 'endorsements', ['event_id'], unique=False)
    op.create_foreign_key(None, 'endorsements', 'event', ['event_id'], ['id'])
    op.drop_column('endorsements', 'message')
    op.drop_column('endorsements', 'category')
    op.add_column('like', sa.Column('endorsement_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_like_endorsement_id'), 'like', ['endorsement_id'], unique=False)
    op.create_unique_constraint('uq_user_endorsement_like', 'like', ['user_id', 'endorsement_id'])
    op.create_foreign_key(None, 'like', 'endorsements', ['endorsement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint('uq_user_endorsement_like', 'like', type_='unique')
    op.drop_index(op.f('ix_like_endorsement_id'), table_name='like')
    op.drop_column('like', 'endorsement_id')
    op.add_column('endorsements', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('endorsements', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'endorsements', type_='foreignkey')
    op.drop_index(op.f('ix_endorsements_event_id'), table_name='endorsements')
    op.create_index(op.f('ix_endorsements_category'), 'endorsements', ['category'], unique=False)
    op.drop_column('endorsements', 'skills')
    op.drop_column('endorsements', 'event_id')
    op.drop_column('endorsements', 'project_id')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_index(op.f('ix_comment_endorsement_id'), table_name='comment')
    op.drop_column('comment', 'endorsement_id')
    # ### end Alembic commands ###
