"""Add organizer to Event

Revision ID: 3d5188c5794d
Revises: ce3eb0a38628
Create Date: 2026-02-08 19:52:33.448101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5188c5794d'
down_revision: Union[str, None] = 'ce3eb0a38628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('organizer_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_event_organizer_id'), 'event', ['organizer_id'], unique=False)
    op.create_foreign_key(None, 'event', 'user', ['organizer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_index(op.f('ix_event_organizer_id'), table_name='event')
    op.drop_column('event', 'organizer_id')
    # ### end Alembic commands ###
