"""add_release_status_fields

Revision ID: 3eccc7b9c018
Revises: c73bbec99272
Create Date: 2026-02-15 21:35:11.772787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eccc7b9c018'
down_revision: Union[str, None] = 'c73bbec99272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('endorsements_event_id_fkey'), 'endorsements', type_='foreignkey')
    op.create_foreign_key(None, 'endorsements', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.alter_column('event', 'has_awards',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('releaseworkitem', sa.Column('status', sa.String(), nullable=True))
    op.add_column('releaseworkitem', sa.Column('completed_at', sa.String(), nullable=True))
    op.create_index(op.f('ix_releaseworkitem_poc_id'), 'releaseworkitem', ['poc_id'], unique=False)
    op.create_foreign_key(None, 'releaseworkitem', 'user', ['poc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'releaseworkitem', type_='foreignkey')
    op.drop_index(op.f('ix_releaseworkitem_poc_id'), table_name='releaseworkitem')
    op.drop_column('releaseworkitem', 'completed_at')
    op.drop_column('releaseworkitem', 'status')
    op.alter_column('event', 'has_awards',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'endorsements', type_='foreignkey')
    op.create_foreign_key(op.f('endorsements_event_id_fkey'), 'endorsements', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###
