"""Restore ReleaseWorkItem table

Revision ID: 431b3b847d9b
Revises: b055bd3c16a6
Create Date: 2026-02-09 10:05:32.217286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '431b3b847d9b'
down_revision: Union[str, None] = 'b055bd3c16a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releaseworkitem',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('release_version', sa.String(), nullable=False),
    sa.Column('unit_testing_checked', sa.Boolean(), nullable=False),
    sa.Column('unit_testing_date', sa.String(), nullable=True),
    sa.Column('system_testing_checked', sa.Boolean(), nullable=False),
    sa.Column('system_testing_date', sa.String(), nullable=True),
    sa.Column('int_testing_checked', sa.Boolean(), nullable=False),
    sa.Column('int_testing_date', sa.String(), nullable=True),
    sa.Column('pvs_testing', sa.Boolean(), nullable=False),
    sa.Column('pvs_intake_number', sa.String(), nullable=True),
    sa.Column('warranty_call_needed', sa.Boolean(), nullable=False),
    sa.Column('confluence_updated', sa.Boolean(), nullable=False),
    sa.Column('csca_intake', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releaseworkitem_id'), 'releaseworkitem', ['id'], unique=False)
    op.create_index(op.f('ix_releaseworkitem_release_version'), 'releaseworkitem', ['release_version'], unique=False)
    op.create_index(op.f('ix_releaseworkitem_team_name'), 'releaseworkitem', ['team_name'], unique=False)
    op.create_index(op.f('ix_releaseworkitem_title'), 'releaseworkitem', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releaseworkitem_title'), table_name='releaseworkitem')
    op.drop_index(op.f('ix_releaseworkitem_team_name'), table_name='releaseworkitem')
    op.drop_index(op.f('ix_releaseworkitem_release_version'), table_name='releaseworkitem')
    op.drop_index(op.f('ix_releaseworkitem_id'), table_name='releaseworkitem')
    op.drop_table('releaseworkitem')
    # ### end Alembic commands ###
