"""Add VotingStatus and update Vote nominee_id

Revision ID: 7c32dafef44c
Revises: 3d5188c5794d
Create Date: 2026-02-08 20:13:14.888885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c32dafef44c'
down_revision: Union[str, None] = '3d5188c5794d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votingstatus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_voting_open', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_votingstatus_id'), 'votingstatus', ['id'], unique=False)
    op.add_column('vote', sa.Column('nominee_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_vote_nominee_id'), 'vote', ['nominee_id'], unique=False)
    op.drop_constraint(op.f('vote_nominator_id_fkey'), 'vote', type_='foreignkey')
    op.drop_constraint(op.f('vote_award_category_id_fkey'), 'vote', type_='foreignkey')
    op.create_foreign_key(None, 'vote', 'awardcategory', ['award_category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vote', 'user', ['nominator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'vote', 'user', ['nominee_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vote', 'nominee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('nominee', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.drop_constraint(None, 'vote', type_='foreignkey')
    op.create_foreign_key(op.f('vote_award_category_id_fkey'), 'vote', 'awardcategory', ['award_category_id'], ['id'])
    op.create_foreign_key(op.f('vote_nominator_id_fkey'), 'vote', 'user', ['nominator_id'], ['id'])
    op.drop_index(op.f('ix_vote_nominee_id'), table_name='vote')
    op.drop_column('vote', 'nominee_id')
    op.drop_index(op.f('ix_votingstatus_id'), table_name='votingstatus')
    op.drop_table('votingstatus')
    # ### end Alembic commands ###
