"""Add category and message to endorsements

Revision ID: 7fc2238554d9
Revises: 1be0a32c5e8b
Create Date: 2026-02-14 18:20:44.361944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc2238554d9'
down_revision: Union[str, None] = '1be0a32c5e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endorsements', sa.Column('category', sa.String(), nullable=False))
    op.add_column('endorsements', sa.Column('message', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endorsements', 'message')
    op.drop_column('endorsements', 'category')
    # ### end Alembic commands ###
