"""add_team_update_table

Revision ID: 8976fba7a26f
Revises: d305987551af
Create Date: 2026-02-08 18:00:08.510408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8976fba7a26f'
down_revision: Union[str, None] = 'd305987551af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamupdate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teamupdate_id'), 'teamupdate', ['id'], unique=False)
    op.create_index(op.f('ix_teamupdate_team_id'), 'teamupdate', ['team_id'], unique=False)
    op.create_index(op.f('ix_teamupdate_user_id'), 'teamupdate', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teamupdate_user_id'), table_name='teamupdate')
    op.drop_index(op.f('ix_teamupdate_team_id'), table_name='teamupdate')
    op.drop_index(op.f('ix_teamupdate_id'), table_name='teamupdate')
    op.drop_table('teamupdate')
    # ### end Alembic commands ###
