"""add_event_timezone_endtime

Revision ID: a084714c552c
Revises: b6d5e4f3a2c1
Create Date: 2026-02-14 14:19:37.565107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a084714c552c'
down_revision: Union[str, None] = 'b6d5e4f3a2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_entity_id'), 'activity_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_log_entity_type'), 'activity_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_log_id'), 'activity_log', ['id'], unique=False)
    op.create_index(op.f('ix_activity_log_user_id'), 'activity_log', ['user_id'], unique=False)
    op.create_table('entity_reference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_entity_type', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=False),
    sa.Column('target_entity_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_reference_id'), 'entity_reference', ['id'], unique=False)
    op.create_index(op.f('ix_entity_reference_source_entity_id'), 'entity_reference', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_reference_source_entity_type'), 'entity_reference', ['source_entity_type'], unique=False)
    op.create_index(op.f('ix_entity_reference_target_entity_id'), 'entity_reference', ['target_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_reference_target_entity_type'), 'entity_reference', ['target_entity_type'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('social_links', sa.JSON(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=False)
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=True)
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.alter_column('endorsements', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('endorsements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_endorsements_category'), 'endorsements', ['category'], unique=False)
    op.create_index(op.f('ix_endorsements_giver_id'), 'endorsements', ['giver_id'], unique=False)
    op.create_index(op.f('ix_endorsements_receiver_id'), 'endorsements', ['receiver_id'], unique=False)
    op.add_column('event', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('timezone', sa.String(), nullable=False))
    op.add_column('event_participants', sa.Column('rsvp_at', sa.DateTime(), nullable=True))
    op.alter_column('event_participants', 'rsvp_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event_participants', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('event_participants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_event_participants_event_id'), 'event_participants', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_participants_user_id'), 'event_participants', ['user_id'], unique=False)
    op.drop_constraint(op.f('event_participants_user_id_fkey'), 'event_participants', type_='foreignkey')
    op.drop_constraint(op.f('event_participants_event_id_fkey'), 'event_participants', type_='foreignkey')
    op.create_foreign_key(None, 'event_participants', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_participants', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.add_column('notification_preferences', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('notification_preferences', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('uix_user_notif_pref'), 'notification_preferences', type_='unique')
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('releases_v2', 'completion_percentage',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('releases_v2', 'health_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('releases_v2', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('releases_v2', 'updated_at')
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('tasks', 'created_by_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('tasks', 'updated_at')
    op.alter_column('test_executions', 'status',
               existing_type=postgresql.ENUM('PASS', 'FAIL', 'BLOCKED', 'SKIPPED', 'PENDING', name='testexecutionstatus'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('test_executions', 'comments',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('test_executions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_test_executions_cycle_id'), 'test_executions', ['cycle_id'], unique=False)
    op.drop_column('test_executions', 'updated_at')
    op.alter_column('testing_cycles', 'status',
               existing_type=postgresql.ENUM('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'ABORTED', name='testcyclestatus'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('testing_cycles', 'pass_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('testing_cycles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_testing_cycles_release_id'), 'testing_cycles', ['release_id'], unique=False)
    op.drop_column('testing_cycles', 'updated_at')
    op.alter_column('work_items_v2', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('work_items_v2', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_work_items_v2_assignee_id'), 'work_items_v2', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_work_items_v2_release_id'), 'work_items_v2', ['release_id'], unique=False)
    op.create_index(op.f('ix_work_items_v2_team_id'), 'work_items_v2', ['team_id'], unique=False)
    op.drop_column('work_items_v2', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_items_v2', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_work_items_v2_team_id'), table_name='work_items_v2')
    op.drop_index(op.f('ix_work_items_v2_release_id'), table_name='work_items_v2')
    op.drop_index(op.f('ix_work_items_v2_assignee_id'), table_name='work_items_v2')
    op.alter_column('work_items_v2', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_items_v2', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('testing_cycles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_testing_cycles_release_id'), table_name='testing_cycles')
    op.alter_column('testing_cycles', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('testing_cycles', 'pass_rate',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('testing_cycles', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'ABORTED', name='testcyclestatus'),
               nullable=True)
    op.add_column('test_executions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_test_executions_cycle_id'), table_name='test_executions')
    op.alter_column('test_executions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_executions', 'comments',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('test_executions', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PASS', 'FAIL', 'BLOCKED', 'SKIPPED', 'PENDING', name='testexecutionstatus'),
               nullable=True)
    op.add_column('tasks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_by_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               nullable=True)
    op.alter_column('tasks', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('TODO', 'IN_PROGRESS', 'DONE', name='taskstatus'),
               nullable=True)
    op.alter_column('tasks', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('releases_v2', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('releases_v2', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('releases_v2', 'health_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('releases_v2', 'completion_percentage',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.create_unique_constraint(op.f('uix_user_notif_pref'), 'notification_preferences', ['user_id', 'notification_type', 'channel'], postgresql_nulls_not_distinct=False)
    op.alter_column('notification_preferences', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('notification_preferences', 'updated_at')
    op.drop_constraint(None, 'event_participants', type_='foreignkey')
    op.drop_constraint(None, 'event_participants', type_='foreignkey')
    op.create_foreign_key(op.f('event_participants_event_id_fkey'), 'event_participants', 'event', ['event_id'], ['id'])
    op.create_foreign_key(op.f('event_participants_user_id_fkey'), 'event_participants', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_event_participants_user_id'), table_name='event_participants')
    op.drop_index(op.f('ix_event_participants_event_id'), table_name='event_participants')
    op.alter_column('event_participants', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('event_participants', 'attended',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('event_participants', 'rsvp_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('event_participants', 'rsvp_at')
    op.drop_column('event', 'timezone')
    op.drop_column('event', 'end_time')
    op.drop_index(op.f('ix_endorsements_receiver_id'), table_name='endorsements')
    op.drop_index(op.f('ix_endorsements_giver_id'), table_name='endorsements')
    op.drop_index(op.f('ix_endorsements_category'), table_name='endorsements')
    op.alter_column('endorsements', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('endorsements', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('profiles',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('social_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey'))
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_entity_reference_target_entity_type'), table_name='entity_reference')
    op.drop_index(op.f('ix_entity_reference_target_entity_id'), table_name='entity_reference')
    op.drop_index(op.f('ix_entity_reference_source_entity_type'), table_name='entity_reference')
    op.drop_index(op.f('ix_entity_reference_source_entity_id'), table_name='entity_reference')
    op.drop_index(op.f('ix_entity_reference_id'), table_name='entity_reference')
    op.drop_table('entity_reference')
    op.drop_index(op.f('ix_activity_log_user_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_entity_type'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_entity_id'), table_name='activity_log')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
