"""Add completion and release date

Revision ID: b055bd3c16a6
Revises: 7c32dafef44c
Create Date: 2026-02-09 10:02:03.965730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b055bd3c16a6'
down_revision: Union[str, None] = '7c32dafef44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_releaseworkitem_id'), table_name='releaseworkitem')
    op.drop_index(op.f('ix_releaseworkitem_release_version'), table_name='releaseworkitem')
    op.drop_index(op.f('ix_releaseworkitem_team_name'), table_name='releaseworkitem')
    op.drop_index(op.f('ix_releaseworkitem_title'), table_name='releaseworkitem')
    op.drop_table('releaseworkitem')
    op.alter_column('votingstatus', 'results_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('votingstatus', 'results_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('releaseworkitem',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit_testing_checked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('unit_testing_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('system_testing_checked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('system_testing_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('int_testing_checked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('int_testing_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pvs_testing', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('pvs_intake_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('warranty_call_needed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('confluence_updated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('csca_intake', sa.VARCHAR(), server_default=sa.text("'No'::character varying"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('releaseworkitem_pkey'))
    )
    op.create_index(op.f('ix_releaseworkitem_title'), 'releaseworkitem', ['title'], unique=False)
    op.create_index(op.f('ix_releaseworkitem_team_name'), 'releaseworkitem', ['team_name'], unique=False)
    op.create_index(op.f('ix_releaseworkitem_release_version'), 'releaseworkitem', ['release_version'], unique=False)
    op.create_index(op.f('ix_releaseworkitem_id'), 'releaseworkitem', ['id'], unique=False)
    # ### end Alembic commands ###
