"""sync_supabase_schema

Revision ID: b5cbee2d679b
Revises: 3eccc7b9c018
Create Date: 2026-02-16 02:20:36.783676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cbee2d679b'
down_revision: Union[str, None] = '3eccc7b9c018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_vote',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('voter_id', sa.String(), nullable=False),
    sa.Column('nominee_id', sa.String(), nullable=False),
    sa.Column('award_category', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nominee_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_vote_award_category'), 'event_vote', ['award_category'], unique=False)
    op.create_index(op.f('ix_event_vote_event_id'), 'event_vote', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_vote_id'), 'event_vote', ['id'], unique=False)
    op.create_index(op.f('ix_event_vote_nominee_id'), 'event_vote', ['nominee_id'], unique=False)
    op.create_index(op.f('ix_event_vote_voter_id'), 'event_vote', ['voter_id'], unique=False)
    op.add_column('event', sa.Column('voting_required', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('releaseworkitem', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('releaseworkitem', 'description')
    op.drop_column('event', 'voting_required')
    op.drop_index(op.f('ix_event_vote_voter_id'), table_name='event_vote')
    op.drop_index(op.f('ix_event_vote_nominee_id'), table_name='event_vote')
    op.drop_index(op.f('ix_event_vote_id'), table_name='event_vote')
    op.drop_index(op.f('ix_event_vote_event_id'), table_name='event_vote')
    op.drop_index(op.f('ix_event_vote_award_category'), table_name='event_vote')
    op.drop_table('event_vote')
    # ### end Alembic commands ###
