"""add_reaction_to_feedback

Revision ID: b7c385a7ce0f
Revises: 7fc2238554d9
Create Date: 2026-02-14 21:47:31.475984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c385a7ce0f'
down_revision: Union[str, None] = '7fc2238554d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('reaction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'reaction')
    # ### end Alembic commands ###
