"""add_reply_column_real

Revision ID: ba63789f87b2
Revises: 52b799552581
Create Date: 2026-02-14 22:10:21.789961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba63789f87b2'
down_revision: Union[str, None] = '52b799552581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('reply', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'reply')
    # ### end Alembic commands ###
