"""Simplify feedback schema - remove type and sentiment

Revision ID: ee34f9989ddb
Revises: f8198489d80d
Create Date: 2026-02-08 19:10:11.164821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee34f9989ddb'
down_revision: Union[str, None] = 'f8198489d80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('feedback_to_user_id_fkey'), 'feedback', type_='foreignkey')
    op.drop_constraint(op.f('feedback_from_user_id_fkey'), 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'user', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feedback', 'user', ['from_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('feedback', 'type')
    op.drop_column('feedback', 'sentiment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('sentiment', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('feedback', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(op.f('feedback_from_user_id_fkey'), 'feedback', 'user', ['from_user_id'], ['id'])
    op.create_foreign_key(op.f('feedback_to_user_id_fkey'), 'feedback', 'user', ['to_user_id'], ['id'])
    # ### end Alembic commands ###
