"""Add cascade delete to TeamUpdate

Revision ID: f8198489d80d
Revises: 6896c7158709
Create Date: 2026-02-08 18:45:04.644701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8198489d80d'
down_revision: Union[str, None] = '6896c7158709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('teamupdate_user_id_fkey'), 'teamupdate', type_='foreignkey')
    op.drop_constraint(op.f('teamupdate_team_id_fkey'), 'teamupdate', type_='foreignkey')
    op.create_foreign_key(None, 'teamupdate', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teamupdate', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teamupdate', type_='foreignkey')
    op.drop_constraint(None, 'teamupdate', type_='foreignkey')
    op.create_foreign_key(op.f('teamupdate_team_id_fkey'), 'teamupdate', 'team', ['team_id'], ['id'])
    op.create_foreign_key(op.f('teamupdate_user_id_fkey'), 'teamupdate', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
